name: caspr_new
channels:
  - biobuilds
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - appdirs=1.4.3
  - appnope=0.1.0
  - backcall=0.1.0
  - bioconductor-annotate=1.58.0
  - bioconductor-annotationdbi=1.42.1
  - bioconductor-biobase=2.40.0
  - bioconductor-biocgenerics=0.26.0
  - bioconductor-genefilter=1.62.0
  - bioconductor-iranges=2.14.12
  - bioconductor-s4vectors=0.18.3
  - bioconductor-sva=3.15.0
  - blas=1.0
  - bwidget=1.9.11
  - bz2file=0.98
  - bzip2=1.0.6
  - ca-certificates=2018.12.5
  - cairo=1.14.12
  - cctools=895
  - certifi=2018.8.24
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - click=6.7
  - compiler-rt=4.0.1
  - curl=7.61.1
  - cutadapt=1.18
  - db=6.2.32
  - db-utils=6.2.32
  - decorator=4.3.0
  - docutils=0.14
  - fastqc=0.11.8
  - fastx-toolkit=0.0.14
  - flask=1.0.2
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gdbm=1.18.1
  - gettext=0.19.8.1
  - gfortran_osx-64=4.8.5
  - glib=2.56.2
  - gnuplot=5.0.0
  - graphite2=1.3.13
  - gsl=2.4
  - harfbuzz=1.8.8
  - icu=58.2
  - intel-openmp=2019.1
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - itsdangerous=0.24
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - krb5=1.16.1
  - ld64=274.2
  - libcurl=7.61.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libdb=6.2.32
  - libdeflate=1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgd=2.1.0
  - libgfortran=3.0.1
  - libgtextutils=0.7
  - libiconv=1.15
  - libopenblas=0.3.3
  - libpng=1.6.36
  - libssh2=1.8.0
  - libtiff=4.0.10
  - libxml2=2.9.9
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - llvm-openmp=4.0.1
  - mageck=0.5.8
  - mageck-vispr=0.5.4
  - make=4.2.1
  - markupsafe=1.0
  - mkl=2018.0.3
  - ncurses=6.1
  - numpy=1.12.1
  - openjdk=8.0.152
  - openssl=1.0.2p
  - pandas=0.19.2
  - pango=1.42.4
  - parso=0.3.1
  - pcre=8.42
  - perl=5.22.0
  - perl-gd=2.56
  - perl-gdgraph=1.49
  - perl-gdtextutil=0.86
  - perl-perlio-gzip=0.19
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pigz=2.4
  - pip=10.0.1
  - pixman=0.36.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pygments=2.2.0
  - python=3.5.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyyaml=3.13
  - r=3.5.1
  - r-assertthat=0.2.0
  - r-base=3.5.1
  - r-bh=1.66.0_1
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-boot=1.3_20
  - r-class=7.3_14
  - r-cli=1.0.0
  - r-cluster=2.0.7_1
  - r-codetools=0.2_15
  - r-crayon=1.3.4
  - r-dbi=1.0.0
  - r-dbplyr=1.2.2
  - r-digest=0.6.15
  - r-dplyr=0.7.6
  - r-fansi=0.2.3
  - r-foreign=0.8_71
  - r-glue=1.3.0
  - r-kernsmooth=2.23_15
  - r-lattice=0.20_35
  - r-magrittr=1.5
  - r-mass=7.3_50
  - r-matrix=1.2_14
  - r-memoise=1.1.0
  - r-mgcv=1.8_24
  - r-nlme=3.1_137
  - r-nnet=7.3_12
  - r-pillar=1.3.0
  - r-pkgconfig=2.0.1
  - r-plogr=0.2.0
  - r-prettyunits=1.0.2
  - r-purrr=0.2.5
  - r-r6=2.2.2
  - r-rcpp=0.12.18
  - r-rcurl=1.95_4.11
  - r-recommended=3.5.1
  - r-rlang=0.2.1
  - r-rpart=4.1_13
  - r-rsqlite=2.1.1
  - r-spatial=7.3_11
  - r-survival=2.42_6
  - r-tibble=1.4.2
  - r-tidyselect=0.2.4
  - r-utf8=1.1.4
  - r-xml=3.98_1.12
  - r-xtable=1.8_2
  - readline=7.0
  - rpy2=2.9.1
  - samtools=1.9
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - six=1.11.0
  - snakemake=3.6.1
  - sqlite=3.26.0
  - star=2.6.1b
  - tk=8.6.8
  - tktable=2.10
  - traitlets=4.3.2
  - vispr=0.4.14
  - wcwidth=0.1.7
  - werkzeug=0.14.1
  - wheel=0.31.1
  - xopen=0.4.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
