site_name: CASPR
docs_dir: pages
site_dir: site

repo_name: 'judithbergada/CASPR'
repo_url: 'https://github.com/judithbergada/CASPR'

# Copyright
copyright: 'Copyright &copy; 2018 Judith Bergadà Pijuan'

nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: all_inclusive
  palette:
    primary: green
    accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.superfences

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/judithbergada/CASPR
