site_name: CASPR
docs_dir: pages
site_dir: site

repo_name: 'judithbergada/CASPR'
repo_url: 'https://github.com/judithbergada/CASPR'
edit_uri: 'tree/master/docs/pages/'

# Google Analytics
google_analytics:
  - UA-139052696-1
  - auto

# Copyright
copyright: 'Copyright &copy; 2018 Judith Bergadà Pijuan'

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Tutorial: tutorial.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: images/logo.svg
  palette:
    primary: green
    accent: indigo

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite

# Customization
extra:
  social:
    - type: fontawesome/brands/github
      link: https://github.com/judithbergada/CASPR
